// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtA9J6ez_lSoy42ZOmYSddtmvE86orAqc',
    appId: '1:526440254543:web:c41a7680aa2d3c37fc6e3a',
    messagingSenderId: '526440254543',
    projectId: 'headphone-app',
    authDomain: 'headphone-app.firebaseapp.com',
    storageBucket: 'headphone-app.firebasestorage.app',
    measurementId: 'G-69G6RDRTP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjIib04uZB6gYZ3J9wpreJ2mvN3KdsCc',
    appId: '1:526440254543:android:63052d3f83cf51effc6e3a',
    messagingSenderId: '526440254543',
    projectId: 'headphone-app',
    storageBucket: 'headphone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTFACIxjfAMBUK2b8wkxOFmD6ehLmYUE',
    appId: '1:526440254543:ios:908479b90b801d45fc6e3a',
    messagingSenderId: '526440254543',
    projectId: 'headphone-app',
    storageBucket: 'headphone-app.firebasestorage.app',
    iosBundleId: 'com.example.headphoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGTFACIxjfAMBUK2b8wkxOFmD6ehLmYUE',
    appId: '1:526440254543:ios:908479b90b801d45fc6e3a',
    messagingSenderId: '526440254543',
    projectId: 'headphone-app',
    storageBucket: 'headphone-app.firebasestorage.app',
    iosBundleId: 'com.example.headphoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtA9J6ez_lSoy42ZOmYSddtmvE86orAqc',
    appId: '1:526440254543:web:42a592769255886afc6e3a',
    messagingSenderId: '526440254543',
    projectId: 'headphone-app',
    authDomain: 'headphone-app.firebaseapp.com',
    storageBucket: 'headphone-app.firebasestorage.app',
    measurementId: 'G-NXPBKRXDRT',
  );
}
